issueTrackerURL = "https://github.com/nexusnode/crafting-dead/issues"
license = "GPL v3.0"
loaderVersion = "[27,)"
modLoader = "javafml"

[[mods]]
authors = "Sm0keySa1m0n"
credits = "Sm0keySa1m0n"
displayName = "Crafting Dead Immerse"
displayURL = "www.craftingdead.com"
modId = "craftingdeadimmerse"
version = "${file.jarVersion}"

[[dependencies.craftingdeadimmerse]]
mandatory = true
modId = "craftingdead"
side = "BOTH"
versionRange = "[1.6.0-alpha,)"

[[dependencies.craftingdeadimmerse]]
mandatory = true
modId = "forge"
ordering = "NONE"
side = "BOTH"
versionRange = "[36.1.0,)"
